# Generated by Django 5.1.6 on 2025-02-12 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='evolves_from_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolves_to', to='pokemons.species'),
        ),
    ]
