# Generated by Django 5.1.6 on 2025-02-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_species_evolves_from_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(null=True, related_name='pokemons', to='pokemons.ability'),
        ),
    ]
