# Generated by Django 5.1.6 on 2025-02-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_pokemon_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='pokemons.species'),
        ),
    ]
