# Generated by Django 5.1.6 on 2025-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_alter_pokemon_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(related_name='pokemons', to='pokemons.move'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(related_name='pokemons', to='pokemons.ability'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='held_items',
            field=models.ManyToManyField(related_name='pokemons', to='pokemons.item'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_stats',
            field=models.ManyToManyField(related_name='pokemons', to='pokemons.pokemonstat'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemons', to='pokemons.pokemontype'),
        ),
    ]
