# Generated by Django 5.1.6 on 2025-02-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0005_pokemon_moves_alter_pokemon_abilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemons', to='pokemons.type'),
        ),
        migrations.DeleteModel(
            name='PokemonType',
        ),
    ]
